url: https://dvirla.github.io
# baseurl: /applied-data-scientist-portfolio

# Site settings
title: Dvir Lafer - Applied Data Scientist
email: dvirla84@gmail.com
description: "Dvir Lafer - Applied Data Scientist freelancer. From POC and acdemic researched to deployed AI models, I will help you unleash the insights from your data using variuos AI models."


# Team names, titles and social links
people:
- name: Dvir Lafer
  pic: dvir-lafer-cropped
  social:
    - title: github
      url: http://github.com/dvirla
    - title: linkedin
      url: https://www.linkedin.com/in/dvir-lafer/
    - title: facebook
      url: https://www.facebook.com/dvir.lafer

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/dvir.lafer
  - title: github
    url: http://github.com/dvirla
  - title: linkedin
    url: https://www.linkedin.com/in/dvir-lafer/

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty