url: https://dvirla.github.io
# baseurl: /applied-data-scientist-portfolio

# Site settings
title: Dvir Lafer - Applied Data Scientist
email: dvirla84@gmail.com
description: "Dvir Lafer - Applied Data Scientist freelancer. From POC and acdemic researched to deployed AI models, I will help you unleash the insights from your data using variuos AI models."


# Team names, titles and social links
# people:
# - name: Kay Garland
#   pic: 1
#   position: Lead Designer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: stack-overflow
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  - title: facebook
    url: https://www.facebook.com/dvir.lafer
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket 
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/dvirla
  - title: linkedin
    url: https://www.linkedin.com/in/dvir-lafer/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty